import { bindActionCreators } from 'redux';

import {
  userRegisterRequest,
  userLoginRequest,
  userLoginSucces,
  userLoginStatus,
  userLoginFailure,
  resetPasswordRequest,
  resetlogout,
  getEmailRequest,
  resetPasswordLinkRequest,
  logoutRequest,
  // Forgot View Actions
  openForgotPasswordView,
  openPasswordRecoveryConfirmationView,
  openPasswordRecoverySuccessView,
  openResetLinkConfirmationView,
  openResetLinkRecoverySuccessView,
  openWelcomeView,
  // Auth View Actions
  openLoginView,
  openSignupView,
  openAuthForgotPasswordView,
  openAuthWelcomeView,
  resetPasswordInAppRequest,
} from './authentication';

import {
  getPendingBets,
  getPendingComboBets,
  getCashoutComboBets,
  getResolvedBets,
  getResolvedComboBets,
  resetResolvedBets,
} from './dashboard';

import { setSelfieWithGovtIdImage, setGovtIdProof } from './newEditProfile';

import {
  getProfileRequest,
  resetProfileRequest,
  uploadKycImageRequest,
  updateWalletAmount,
} from './profile';

import { setCurrentOrientation } from './orientation';

import {
  getCasinoRequest,
  getCasinoSuccess,
  getCasinoFailure,
  getCasinoInitGameSessionRequest,
  getCasinoInitGameSessionSuccess,
  getCasinoInitGameSessionFailure,
  onTabSelect,
  onFreeSpinSelect,
  onLobbySelect,
  onMobileSelect,
  setProvidersSelect,
} from './casinoAction';

import {
  getLiveCasinoRequest,
  getLiveCasinoFailure,
  getLiveCasinoSuccess,
  getLiveCasinoInitGameSessionRequest,
  getLiveCasinoInitGameSessionSuccess,
  getLiveCasinoInitGameSessionFailure,
  liveCasinoOnTabSelect,
  onLiveFreeSpinSelect,
  onLiveLobbySelect,
  onLiveMobileSelect,
  setLiveProvidersSelect,
} from './liveCasinoActions';

import {
  getVirtualGamesRequest,
  getVirtualGamesFailure,
  getVirtualGamesSuccess,
  getVirtualGamesInitGameSessionRequest,
  getVirtualGamesInitGameSessionSuccess,
  getVirtualGamesInitGameSessionFailure,
  onVirtualGamesTabSelect,
  onVirtualGamesFreeSpinSelect,
  onVirtualGamesLobbySelect,
  onVirtualGamesMobileSelect,
  setVirtualGamesProvidersSelect,
} from './virtualGamesAction'

import {
  getLiveMatchesRequest,
  getLiveMatchesSuccess,
  getLiveMatchesFailure,
  addToMyFavoritesRequest,
  addToMyFavoritesSuccess,
  addToMyFavoritesFailure,
  removeFromMyFavoritesRequest,
  removeFromMyFavoritesSuccess,
  removeFromMyFavoritesFailure,
  getMyFavoritesRequest,
  getMyFavoritesSuccess,
  getMyFavoritesFailure,
} from './liveBetting';

import {
  getUserDetailsRequest,
  getUserDetailsSuccess,
  getUserDetailsFailure,
  postTransferAmountRequest,
  postTransferAmountSuccess,
  postTransferAmountFailure,
  getTransactionHistoryRequest,
  getTransactionHistorySuccess,
  getTransactionHistoryFailure,
} from './fundTransferAction';

import {
  getTodayRequest,
  getTodaySuccess,
  getTodayFailure,
} from './todayAction';

import { store } from '../store';

import {
  getSportsRequest,
  getSportsSuccess,
  getSportsFailure,
  getTournamentsWithMatchesRequest,
  getTournamentsWithMatchesSuccess,
  getTournamentsWithMatchesFailure,
  getTournamentsWithMatchesInPlayRequest,
  getTournamentsWithMatchesInPlaySuccess,
  getTournamentsWithMatchesInPlayFailure,
  getTournamentsWithMatchesTodayRequest,
  getTournamentsWithMatchesTodaySuccess,
  getTournamentsWithMatchesTodayFailure,
  onPressMatch,
  onSelectSport,
  onBetSlipOddsChange,
  setBetSlips,
  deleteBetSlips,
  clearAllBetSlips,
  setBetSlipContainerVisiblity,
  setTournamentsFilterType,
  setEnterStakeValueInBetSlipVisiblity,
  updateBetSlips,
  getMarketsForSelectedMatchRequest,
  getMarketsForSelectedMatchSuccess,
  getMarketsForSelectedMatchFailure,
  postBetSlipsRequest,
  postBetSlipsSuccess,
  postBetSlipsFailed,
  postCashoutBetRequest,
  postCashoutBetSuccess,
  postCashoutBetFailed,
  cashoutMismatchError,
  getBetsRequest,
  getBetsSuccess,
  getBetsFailed,
  getMyBetsRequest,
  getMyBetsSuccess,
  getMyBetsFailed,
  updateMarkets,
  updateSelectedMatchScoreAndTime,
} from './mainGamePlayAction';

import {
  getUserLimitRequest,
  setUserLimitRequest,
  getUserDepositRequest,
  setDepositBetAndReminderLimit,
  setTypeOfLimit,
  setSelectedTab,
  selectValue,
  cancelSelection,
  onSelectPickerValue,
  getSettingsRequest,
  getSettingsSuccess,
  getSettingsFailed,
} from './responsibleGambling';

import {
  getCountryListRequest,
  getCountryListSuccess,
  getCountryListFailure,
  getTournamentListRequest,
  getTournamentListSuccess,
  getTournamentListFailure,
  getMatchListRequest,
  getMatchListSuccess,
  getMatchListFailure,
  getAllMarketsRequest,
  getAllMarketsSuccess,
  getAllMarketsFailure,
  getAllSportsRequest,
  getAllSportsSuccess,
  getAllSportsFailure,
} from './listsAction';

const actions = {
  // Profile
  getProfileRequest,
  resetProfileRequest,
  uploadKycImageRequest,
  updateWalletAmount,
  setSelfieWithGovtIdImage,
  setGovtIdProof,
  userRegisterRequest,
  userLoginRequest,
  userLoginSucces,
  userLoginFailure,
  userLoginStatus,
  resetPasswordRequest,
  resetlogout,
  resetPasswordInAppRequest,
  getPendingBets,
  getPendingComboBets,
  getCashoutComboBets,
  getEmailRequest,
  resetPasswordLinkRequest,
  setCurrentOrientation,
  logoutRequest,
  // Forgot Password View Actions
  openForgotPasswordView,
  openPasswordRecoveryConfirmationView,
  openPasswordRecoverySuccessView,
  openResetLinkConfirmationView,
  openResetLinkRecoverySuccessView,
  openWelcomeView,
  // Auth View Actions
  openLoginView,
  openSignupView,
  openAuthForgotPasswordView,
  openAuthWelcomeView,
  getResolvedBets,
  getResolvedComboBets,
  resetResolvedBets,
  getSportsRequest,
  getSportsSuccess,
  getSportsFailure,
  getTournamentsWithMatchesRequest,
  getTournamentsWithMatchesSuccess,
  getTournamentsWithMatchesFailure,
  getTournamentsWithMatchesInPlayRequest,
  getTournamentsWithMatchesInPlaySuccess,
  getTournamentsWithMatchesInPlayFailure,
  getTournamentsWithMatchesTodayRequest,
  getTournamentsWithMatchesTodaySuccess,
  getTournamentsWithMatchesTodayFailure,
  onPressMatch,
  onSelectSport,
  setBetSlips,
  deleteBetSlips,
  clearAllBetSlips,
  setBetSlipContainerVisiblity,
  setTournamentsFilterType,
  setEnterStakeValueInBetSlipVisiblity,
  updateBetSlips,
  getMarketsForSelectedMatchRequest,
  getMarketsForSelectedMatchSuccess,
  getMarketsForSelectedMatchFailure,
  postBetSlipsRequest,
  postBetSlipsSuccess,
  postBetSlipsFailed,
  postCashoutBetRequest,
  postCashoutBetSuccess,
  postCashoutBetFailed,
  cashoutMismatchError,
  getBetsRequest,
  getBetsSuccess,
  getBetsFailed,
  getMyBetsRequest,
  getMyBetsSuccess,
  getMyBetsFailed,
  // settings
  getSettingsRequest,
  getSettingsSuccess,
  getSettingsFailed,
  // responsible gambling
  getUserLimitRequest,
  setUserLimitRequest,
  getUserDepositRequest,
  setDepositBetAndReminderLimit,
  setTypeOfLimit,
  setSelectedTab,
  selectValue,
  cancelSelection,
  onSelectPickerValue,
  // main game play
  updateMarkets,
  updateSelectedMatchScoreAndTime,
  onBetSlipOddsChange,
  // casino
  getCasinoRequest,
  getCasinoSuccess,
  getCasinoFailure,
  getCasinoInitGameSessionRequest,
  getCasinoInitGameSessionSuccess,
  getCasinoInitGameSessionFailure,
  onTabSelect,
  onFreeSpinSelect,
  onLobbySelect,
  onMobileSelect,
  setProvidersSelect,
  // live casino
  getLiveCasinoRequest,
  getLiveCasinoFailure,
  getLiveCasinoSuccess,
  getLiveCasinoInitGameSessionRequest,
  getLiveCasinoInitGameSessionSuccess,
  getLiveCasinoInitGameSessionFailure,
  liveCasinoOnTabSelect,
  onLiveFreeSpinSelect,
  onLiveLobbySelect,
  onLiveMobileSelect,
  setLiveProvidersSelect,
  // virtual games
  getVirtualGamesRequest,
  getVirtualGamesFailure,
  getVirtualGamesSuccess,
  getVirtualGamesInitGameSessionRequest,
  getVirtualGamesInitGameSessionSuccess,
  getVirtualGamesInitGameSessionFailure,
  onVirtualGamesTabSelect,
  onVirtualGamesFreeSpinSelect,
  onVirtualGamesLobbySelect,
  onVirtualGamesMobileSelect,
  setVirtualGamesProvidersSelect,
  // sports list
  getAllSportsRequest,
  getAllSportsSuccess,
  getAllSportsFailure,
  // country list
  getCountryListRequest,
  getCountryListSuccess,
  getCountryListFailure,
  // tournament List
  getTournamentListRequest,
  getTournamentListSuccess,
  getTournamentListFailure,
  // match List
  getMatchListRequest,
  getMatchListSuccess,
  getMatchListFailure,
  // market list
  getAllMarketsRequest,
  getAllMarketsSuccess,
  getAllMarketsFailure,
  // live betting
  getLiveMatchesRequest,
  getLiveMatchesSuccess,
  getLiveMatchesFailure,
  addToMyFavoritesRequest,
  addToMyFavoritesSuccess,
  addToMyFavoritesFailure,
  removeFromMyFavoritesRequest,
  removeFromMyFavoritesSuccess,
  removeFromMyFavoritesFailure,
  getMyFavoritesRequest,
  getMyFavoritesSuccess,
  getMyFavoritesFailure,
  // fund transfer
  getUserDetailsRequest,
  getUserDetailsSuccess,
  getUserDetailsFailure,
  postTransferAmountRequest,
  postTransferAmountSuccess,
  postTransferAmountFailure,
  getTransactionHistoryRequest,
  getTransactionHistorySuccess,
  getTransactionHistoryFailure,
  // todays
  getTodayRequest,
  getTodaySuccess,
  getTodayFailure,
};


export default bindActionCreators(actions, store.dispatch);
