// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

export const authenticationLocalizedString = new LocalizedStrings({
// English
  en: {
    // Messages
    // worldSportBook: 'WORLD SPORTSBOOK',
    worldSportBook: '',
    // selectSecurityQuestion: 'Select a security question',
    // incorrectSecurityAnswer: 'Incorrect security answer. Please try again.',
    welcomeText: 'Welcome to Bwinner',
    emailAddress: 'Email address',
    username: 'Username',
    password: 'Password',
    // securityQuestion: 'securityQuestion',
    continueWith: 'OR CONTINUE WITH',
    loginText: 'Email or username',
    signInWith: 'SIGN IN WITH',
    forgotPassword: 'FORGOT PASSWORD',
    signUp: 'Sign Up',
    welcome: 'Welcome',
    signIn: 'Sign In',
    faq: 'FAQ',
    competition: 'Competition',
    oddsConsultants: 'Odds Consultants',
    playingPartners: 'Playing Partners',
    howToPlay: 'How to Play',
    // Documents
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms Of Use',
    rules: 'Rules',
    passwordRecovery: 'Password Recovery',
    validEmail: 'Enter valid email for recovery',
    sendSms: 'SEND VIA SMS',
    recovery: 'RECOVERY',
    passwordRecoverySuccess: 'Password Recovery Success!!',
    sentPasswordInEmail: 'We have sent your password to your email address and phone number of record below:',
    done: 'DONE',
    resetPassword: 'Reset password',
    changePassword: 'Change password',
    passwordSentToMail: 'We will send you an email containing a link to reset your password on your registered email address:',
    reset: 'RESET',
    resetLinkSend: 'Reset password link sent!',
    sentLinkToYourMail: 'An email containing a password reset link has been sent to your email address:',
    emailDosenotArrived: "If email doesn't arrive soon check your spam folder.",
    // answerSecurityQuestion: 'Answer the security question to immediately restore the full access.',
    yourPasswordWillthenBeSent: 'Your Password will then be sent to your email address and phone number of record.',
    // proceedToSecurityQuestion: 'PROCEED TO SECURITY QUESTIONS',
    typeYourAnswer: 'Type your answer',
    selectDifferentQuestion: 'Please answer the security question below.',
    back: 'BACK',
    submit: 'SUBMIT',
    loginCancelledMessage: 'Login cancelled',
    login: 'LOG IN',
    register: 'REGISTER',
    optionalRecovery: 'Optional Recovery',
    // Reset password.
    msgOldPassword: 'Please enter old password.',
    msgNewPassword: 'Please enter new password.',
    msgConfirmPassword: 'Please enter confirm password.',
    msgNotMatchedPassword: 'The new password and confirmation password do not match.',
    oldPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    alreadyHaveAnAccount: 'Already have an account?',
    invalidEmail: 'Please enter a valid email id',
    dontHaveAccount: "Don't have an account?",
  },
});
