// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

export const commonLocalizeStrings = new LocalizedStrings({
  // English
  en: {
    // Messages
    internalServerErrorMessage: 'The request failed due to an internal server error.',
    serverErrorMessage: 'Sorry, Something Went Wrong: Please try again later.',
    sessionErrorMessage: 'Sorry, Your session has expired. Please login again to continue play.',
    noInternetConnection: {
      header: 'No Internet Connection Available',
      message: 'Please check your internet connection.',
    },
    emptyEmailUsernameErrorMessage: 'Please enter email address or username.',
    emptyEmailErrorMessage: 'Please enter email address.',
    invalidEmailErrorMessage: 'Your e-mail is incorrect.',
    emptyUsernameErrorMessage: 'Please enter username.',
    invalidUsernameErrorMessage: 'Username complexity requirement not met. Supports alphabets and numbers no special characters with min 3 and max 30 characters.',
    emptyPasswordErrorMessage: 'Please enter password.',
    invalidPasswordErrorMessage: 'Password complexity requirement not met. Length should be 5-20 characters and include: 1 lowercase, 1 digit',
    incorrectUsernameErrorMessage: 'Your username is incorrect.',
    incorrectPasswordErrorMessage: 'Your password is incorrect.',
    emptySecurityAnswerErrorMessage: 'Please enter answer.',
    workInProgressMessage: 'Work in Progress.',
    enterStakeValue: 'Please enter stake amount to place the bets.',
    pleaseLogin: 'You need to Sign in before continue',
    cashoutContinue: 'Are you sure you want to cashout?',
    matchFinshed: 'Match is completed',
    error: 'Error: ',
    ok: 'Ok',
    cancel: 'Cancel',
    cashout: 'Cashout',
    alert: 'Alert',
    all: 'ALL',
    searchGames: 'Search Games...',
    noResultFound: 'No results found...',
    home: 'home',
    away: 'away',
    noDatatoDisplay: 'There is no data to display',
    noAvailableOdds: 'No odds available for betting',
    noBetPlacedYet: 'No bets has been placed yet.',
    stake: 'Stake:',
    toReturn: 'To Return',
    winAmount: 'Win Amount:',
    lostAmount: 'Lost Amount',
    odds: 'Odds',
    enterStake: 'Enter Stake:',
    toWin: 'To Win:',
    cashoutableAmt: 'Cashed Amount',
    betSlips: 'Bet Slips:',
    outcome: 'Outcome:',
    amount: 'Amount:',
    noBetsToDisplay: 'Currently there is no bets to display.',
    noIntenet: 'No Internet connection',
    currentDeviceOrientation: `Current Device Orientation: `,
    save: 'Save',
    myBets: 'My Bets',
  },
});
