// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

export const poolLocalizeScreens = new LocalizedStrings({
// English
  en: {
    // Messages
    continue: 'Continue',
    next: 'Next',
    join: 'Join',
    noPools: 'You have no current pool matches!!',
    selectPooltoStart: 'Select any pool to start',
    yourCurrentPoolMatches: 'Your current pool matches',
    paymentDetail: 'Payment detail should be there',
    poolName: 'Pool Name: ',
    entryFee: 'Entry Fee: ',
    matches: 'Matches',
    players: 'Players',
    poolPrizing: 'Pool Prizing',
    passwordHeaderText: 'Please enter your password',
    password: 'Password',
    passwordErrorText: 'Invalid password',
    logout: 'LOGOUT',
    winnerTakeAll: '1st: 100%',
    firstPrice: '1st: 60%',
    secondPrice: '2nd: 30%',
    thirdPrice: '3rd: 10%',
    houseTake: 'House:',
    winningRatio: 'Payout: ',
    popUpHeading: 'Are you sure you want to join this pool?',
    numberOfPeoples: 'Number of peoples:',
    minimumBets: 'Minimum bets: ',
    tabAllPools: 'Available Pools',
    tabMyPools: 'My Pools',
    youWon: 'YOU WON',
    youLost: 'YOU LOST',
    peopleJoined: 'Joined',
    scheduledAt: 'Scheduled At:',
    remainingTime: 'Remaining time:',
    matchName: 'Match Name:',
    days: 'days',
    hours: 'hours',
    day: 'day',
    hour: 'hour',
    upcoming: 'Upcoming',
    live: 'Live',
    completed: 'Completed',
    detail: 'Detail',
    qualified: 'QUALIFIED',
    notQualified: 'NOT QUALIFIED',
    leaderboard: 'LEADERBOARD',
    rank: 'Final Place:',
    amount: 'Amount',
    poolTotal: 'Pool total: ',
    totalJoined: 'Total joined: ',
    poolPoints: 'Pool Points: ',
    first: '1st: ',
    second: '2nd: ',
    third: '3rd: ',
    play: 'Play',
    userRank: 'Rank',
    userName: 'User Name',
    apply: 'Apply',
  },
});
